#ifndef BTE_SERVICES_HID_CONSTANTS_H
#define BTE_SERVICES_HID_CONSTANTS_H

#ifdef __cplusplus
extern "C" {
#endif

#define BTE_HID_STATE_READY      0x00
#define BTE_HID_STATE_LISTEN     0x01
#define BTE_HID_STATE_CONNECTING 0x02
#define BTE_HID_STATE_CONNECTED  0x04

#define BTE_HID_CONTROL_CHANNEL 0x11
#define BTE_HID_DATA_CHANNEL    0x13

#define BTE_HID_HDR_TRANS_MASK 0xf0
#define BTE_HID_HDR_PARAM_MASK 0x0f

#define BTE_HID_TRANS_HANDSHAKE   0x00
#define BTE_HID_TRANS_HIDCONTROL  0x10
#define BTE_HID_TRANS_GETREPORT   0x40
#define BTE_HID_TRANS_SETREPORT   0x50
#define BTE_HID_TRANS_GETPROTOCOL 0x60
#define BTE_HID_TRANS_SETPROTOCOL 0x70
#define BTE_HID_TRANS_GETIDLE     0x80
#define BTE_HID_TRANS_SETIDLE     0x90
#define BTE_HID_TRANS_DATA        0xa0
#define BTE_HID_TRANS_DATAC       0xb0

#define BTE_HID_HSHK_OK            0x00
#define BTE_HID_HSHK_NOT_READY     0x01
#define BTE_HID_HSHK_INV_REPORT_ID 0x02
#define BTE_HID_HSHK_NOT_SUPPORTED 0x03
#define BTE_HID_HSHK_INVALID_PARAM 0x04
#define BTE_HID_HSHK_UNKNOWN_ERROR 0x0e
#define BTE_HID_HSHK_FATAL_ERROR   0x0f

#define BTE_HID_CTRL_NOP        0x00
#define BTE_HID_CTRL_HARD_RESET 0x01
#define BTE_HID_CTRL_SOFT_RESET 0x02
#define BTE_HID_CTRL_SUSPEND    0x03
#define BTE_HID_CTRL_RESUME     0x04
#define BTE_HID_CTRL_VC_UNPLUG  0x05

/* BTE_HID data transaction headers */
#define BTE_HID_REP_TYPE_MASK    0x03
#define BTE_HID_REP_SRVD_MASK    0x0c
#define BTE_HID_REP_TYPE_OTHER   0x00
#define BTE_HID_REP_TYPE_INPUT   0x01
#define BTE_HID_REP_TYPE_OUTPUT  0x02
#define BTE_HID_REP_TYPE_FEATURE 0x03

#define BTE_HID_PROTO_BOOT   0x00
#define BTE_HID_PROTO_REPORT 0x01

#ifdef __cplusplus
}
#endif

#endif /* BTE_SERVICES_HID_CONSTANTS_H */
