#ifndef BTE_SDP_CONSTANTS_H
#define BTE_SDP_CONSTANTS_H

/*
 * Protocol identifiers
 */

#define BTE_SDP_PROTO_SDP             0x0001
#define BTE_SDP_PROTO_UDP             0x0002
#define BTE_SDP_PROTO_RFCOMM          0x0003
#define BTE_SDP_PROTO_TCP             0x0004
#define BTE_SDP_PROTO_TCS_BIN         0x0005
#define BTE_SDP_PROTO_TCS_AT          0x0006
#define BTE_SDP_PROTO_ATT             0x0007
#define BTE_SDP_PROTO_OBEX            0x0008
#define BTE_SDP_PROTO_IP              0x0009
#define BTE_SDP_PROTO_FTP             0x000A
#define BTE_SDP_PROTO_HTTP            0x000C
#define BTE_SDP_PROTO_WSP             0x000E
#define BTE_SDP_PROTO_BNEP            0x000F
#define BTE_SDP_PROTO_UPNP            0x0010
#define BTE_SDP_PROTO_HID             0x0011
#define BTE_SDP_PROTO_HC_CONTROL      0x0012
#define BTE_SDP_PROTO_HC_DATA         0x0014
#define BTE_SDP_PROTO_HC_NOTIFICATION 0x0016
#define BTE_SDP_PROTO_AVCTP           0x0017
#define BTE_SDP_PROTO_AVDTP           0x0019
#define BTE_SDP_PROTO_CMTP            0x001B
#define BTE_SDP_PROTO_MCAP_CONTROL    0x001E
#define BTE_SDP_PROTO_MCAP_DATA       0x001F
#define BTE_SDP_PROTO_L2CAP           0x0100

/*
 * Service class identifiers
 */
#define BTE_SDP_SRV_CLASS_SD_SERVICE          0x1000
#define BTE_SDP_SRV_CLASS_BROWSE_GRP_DESC     0x1001
#define BTE_SDP_SRV_CLASS_SERIAL_PORT         0x1101
#define BTE_SDP_SRV_CLASS_LAN_PPP             0x1102
#define BTE_SDP_SRV_CLASS_DIALUP              0x1103
#define BTE_SDP_SRV_CLASS_IR_MCSYNC           0x1104
#define BTE_SDP_SRV_CLASS_OBEX_OP             0x1105
#define BTE_SDP_SRV_CLASS_OBEX_FT             0x1106
#define BTE_SDP_SRV_CLASS_IR_MCSYNC_CMD       0x1107
#define BTE_SDP_SRV_CLASS_HEADSET             0x1108
#define BTE_SDP_SRV_CLASS_CORDLESS_TEL        0x1109
#define BTE_SDP_SRV_CLASS_AUDIO_SOURCE        0x110A
#define BTE_SDP_SRV_CLASS_AUDIO_SINK          0x110B
#define BTE_SDP_SRV_CLASS_AV_REM_CTRL_TARGET  0x110C
#define BTE_SDP_SRV_CLASS_ADV_AUDIO_DIST      0x110D
#define BTE_SDP_SRV_CLASS_AV_REM_CTRL         0x110E
#define BTE_SDP_SRV_CLASS_AV_REM_CTRL_CTRL    0x110F
#define BTE_SDP_SRV_CLASS_INTERCOM            0x1110
#define BTE_SDP_SRV_CLASS_FAX                 0x1111
#define BTE_SDP_SRV_CLASS_HEADSET_AUDIO_GW    0x1112
#define BTE_SDP_SRV_CLASS_WAP                 0x1113
#define BTE_SDP_SRV_CLASS_WAP_CLIENT          0x1114
#define BTE_SDP_SRV_CLASS_PANU                0x1115
#define BTE_SDP_SRV_CLASS_NAP                 0x1116
#define BTE_SDP_SRV_CLASS_GN                  0x1117
#define BTE_SDP_SRV_CLASS_DIRECT_PRINTING     0x1118
#define BTE_SDP_SRV_CLASS_REF_PRINTING        0x1119
#define BTE_SDP_SRV_CLASS_IMAGING             0x111A
#define BTE_SDP_SRV_CLASS_IMAGING_RESPONDER   0x111B
#define BTE_SDP_SRV_CLASS_IMAGING_AUTO_ARCH   0x111C
#define BTE_SDP_SRV_CLASS_IMAGING_REF_OBJ     0x111D
#define BTE_SDP_SRV_CLASS_HANDS_FREE          0x111E
#define BTE_SDP_SRV_CLASS_AG_HANDS_FREE       0x111F
#define BTE_SDP_SRV_CLASS_DIR_PRINT_REF_OBJ   0x1120
#define BTE_SDP_SRV_CLASS_REFLECTED_UI        0x1121
#define BTE_SDP_SRV_CLASS_BASIC_PRINTING      0x1122
#define BTE_SDP_SRV_CLASS_PRINTING_STATUS     0x1123
#define BTE_SDP_SRV_CLASS_HID                 0x1124
#define BTE_SDP_SRV_CLASS_HC_CABLE_REP        0x1125
#define BTE_SDP_SRV_CLASS_HCR_PRINT           0x1126
#define BTE_SDP_SRV_CLASS_HCR_SCAN            0x1127
#define BTE_SDP_SRV_CLASS_COMMON_ISDN_ACCESS  0x1128
#define BTE_SDP_SRV_CLASS_SIM_ACCESS          0x112D
#define BTE_SDP_SRV_CLASS_PHONEBOOK_AC_CLIENT 0x112E
#define BTE_SDP_SRV_CLASS_PHONEBOOK_AC_SERVER 0x112F
#define BTE_SDP_SRV_CLASS_PHONEBOOK_AC_PROF   0x1130
#define BTE_SDP_SRV_CLASS_HEADSET_HS          0x1131
#define BTE_SDP_SRV_CLASS_MSG_ACCESS_SERVER   0x1132
#define BTE_SDP_SRV_CLASS_MSG_NOTIF_SERVER    0x1133
#define BTE_SDP_SRV_CLASS_MSG_ACCESS_PROF     0x1134
#define BTE_SDP_SRV_CLASS_GNSS                0x1135
#define BTE_SDP_SRV_CLASS_GNSS_SERVER         0x1136
#define BTE_SDP_SRV_CLASS_3D_DISPLAY          0x1137
#define BTE_SDP_SRV_CLASS_3D_GLASSES          0x1138
#define BTE_SDP_SRV_CLASS_3D_SYNCH_PROF       0x1139
#define BTE_SDP_SRV_CLASS_MULTI_PROF_SPEC     0x113A
#define BTE_SDP_SRV_CLASS_MPS                 0x113B
#define BTE_SDP_SRV_CLASS_CTN_ACCESS          0x113C
#define BTE_SDP_SRV_CLASS_CTN_NOTIF           0x113D
#define BTE_SDP_SRV_CLASS_CAL_TASK_NOTES      0x113E
#define BTE_SDP_SRV_CLASS_PNP_INFO            0x1200
#define BTE_SDP_SRV_CLASS_GENERIC_NET         0x1201
#define BTE_SDP_SRV_CLASS_GENERIC_FILE_XFER   0x1202
#define BTE_SDP_SRV_CLASS_GENERIC_AUDIO       0x1203
#define BTE_SDP_SRV_CLASS_GENERIC_TEL         0x1204
#define BTE_SDP_SRV_CLASS_UPNP                0x1205
#define BTE_SDP_SRV_CLASS_UPNP_IP             0x1206
#define BTE_SDP_SRV_CLASS_ESDP_UPNP_IP_PAN    0x1300
#define BTE_SDP_SRV_CLASS_ESDP_UPNP_IP_LAP    0x1301
#define BTE_SDP_SRV_CLASS_ESDP_UPNP_L2CAP     0x1302
#define BTE_SDP_SRV_CLASS_VIDEO_SRC           0x1303
#define BTE_SDP_SRV_CLASS_VIDEO_SINK          0x1304
#define BTE_SDP_SRV_CLASS_VIDEO_DIST          0x1305
#define BTE_SDP_SRV_CLASS_HDP                 0x1400
#define BTE_SDP_SRV_CLASS_HDP_SOURCE          0x1401
#define BTE_SDP_SRV_CLASS_HDP_SINK            0x1402

/*
 * Attribute IDs
 * (incomplete: feel free to submot more)
 */

/* Universal attributes */
#define BTE_SDP_ATTR_ID_SRV_RECORD        0x0000
#define BTE_SDP_ATTR_ID_SRV_CLS_ID_LIST   0x0001
#define BTE_SDP_ATTR_ID_SRV_RECORD_STATE  0x0002
#define BTE_SDP_ATTR_ID_SRV_ID            0x0003
#define BTE_SDP_ATTR_ID_PROTO_DESC_LIST   0x0004
#define BTE_SDP_ATTR_ID_BROWSE_GRP_LIST   0x0005
#define BTE_SDP_ATTR_ID_LAND_BASE_ID_LIST 0x0006
#define BTE_SDP_ATTR_ID_SRV_INFO_TTL      0x0007
#define BTE_SDP_ATTR_ID_SRV_AVAIL         0x0008
#define BTE_SDP_ATTR_ID_BT_PROF_DESC_LIST 0x0009
#define BTE_SDP_ATTR_ID_DOC_URL           0x000A
#define BTE_SDP_ATTR_ID_CLIENT_EXEC_URL   0x000B
#define BTE_SDP_ATTR_ID_ICON_URL          0x000C
#define BTE_SDP_ATTR_ID_ADD_PROTO_DESC    0x000D

/* Object Push Profile (OPP) */
#define BTE_SDP_ATTR_ID_GOEP_L2CAP_PSM 0x0200
#define BTE_SDP_ATTR_ID_SRV_VER        0x0300
#define BTE_SDP_ATTR_ID_SUPP_FORMATS   0x0303

/* HID */
#define BTE_SDP_ATTR_ID_HID_DEV_REL_NUM  0x0200
#define BTE_SDP_ATTR_ID_HID_PARSER_VER   0x0201
#define BTE_SDP_ATTR_ID_HID_DEV_SUBCLASS 0x0202
#define BTE_SDP_ATTR_ID_HID_COUNTRY_CODE 0x0203
#define BTE_SDP_ATTR_ID_HID_VIRT_CABLE   0x0204
#define BTE_SDP_ATTR_ID_HID_RECONN_INIT  0x0205
#define BTE_SDP_ATTR_ID_HID_DESC_LIST    0x0206
#define BTE_SDP_ATTR_ID_HID_LANGID_BASE  0x0207
#define BTE_SDP_ATTR_ID_HID_SDP_DISABLE  0x0208
#define BTE_SDP_ATTR_ID_HID_BATTERY_PWR  0x0209
#define BTE_SDP_ATTR_ID_HID_REMOTE_WAKE  0x020A
#define BTE_SDP_ATTR_ID_HID_PROV_VER     0x020B
#define BTE_SDP_ATTR_ID_HID_SUPERVIS_TO  0x020C
#define BTE_SDP_ATTR_ID_HID_NORM_CONN    0x020D
#define BTE_SDP_ATTR_ID_HID_BOOT_DEV     0x020E
#define BTE_SDP_ATTR_ID_HID_SSR_HOST_LAT 0x020F
#define BTE_SDP_ATTR_ID_HID_SSR_HOST_TO  0x0210

/* DID (PNP information) */
#define BTE_SDP_ATTR_ID_DID_SPEC_ID    0x0200
#define BTE_SDP_ATTR_ID_DID_VENDOR_ID  0x0201
#define BTE_SDP_ATTR_ID_DID_PRODUCT_ID 0x0202
#define BTE_SDP_ATTR_ID_DID_VERSION    0x0203
#define BTE_SDP_ATTR_ID_DID_PRIMARY    0x0204
#define BTE_SDP_ATTR_ID_DID_VID_SOURCE 0x0205

#endif /* BTE_SDP_CONSTANTS_H */
